// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4825.FRC_2015.subsystems;

import org.usfirst.frc4825.FRC_2015.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * January 31st 2015 Jonathan Chow
 */
public class BinLift extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController motor = RobotMap.binLiftMotor;
	DigitalInput bottomSwitch = RobotMap.binLiftBottomSwitch;
	DigitalInput upperSwitch = RobotMap.binLiftUpperSwitch;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	@Override
	public void initDefaultCommand() {

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void liftBin() {
		if (upperSwitch.get() == true)
			motor.set(0.5);
		else
			motor.set(0.0);
	}

	public void lowerBin() {
		if (bottomSwitch.get() == true)
			motor.set(-0.5);
		else
			motor.set(0.0);
	}

	public void stopBin() {
		motor.set(0.0);
	}

	public boolean getUpperSwitch() {
		return upperSwitch.get();
	}

	public boolean getBottomSwitch() {
		return bottomSwitch.get();
	}
}
