// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4825.NewRobotDrivetrain;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController candellaSpeedController1;
    public static SpeedController candellaSpeedController2;
    public static RobotDrive candellaRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        candellaSpeedController1 = new Victor(1, 1);
	LiveWindow.addActuator("candella", "Speed Controller 1", (Victor) candellaSpeedController1);
        
        candellaSpeedController2 = new Victor(1, 2);
	LiveWindow.addActuator("candella", "Speed Controller 2", (Victor) candellaSpeedController2);
        
        candellaRobotDrive21 = new RobotDrive(candellaSpeedController1, candellaSpeedController2);
	
        candellaRobotDrive21.setSafetyEnabled(true);
        candellaRobotDrive21.setExpiration(0.1);
        candellaRobotDrive21.setSensitivity(0.5);
        candellaRobotDrive21.setMaxOutput(1.0);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
